services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - microservicessolution-network
    
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Pwd@123456
            - MSSQL_PID=Express 
        ports:
            - "1433:1433"
        networks:
            - microservicessolution-network
    
    productservice:
        build: 
            context: .
            dockerfile: ProductService/Dockerfile
        container_name: productservice
        ports:
           - "5001:80"
        depends_on:
           - sqlserver
           - rabbitmq
        networks:
           - microservicessolution-network
        environment:
           - ASPNETCORE_ENVIRONMENT=Docker
    
    adapterservice:
        build:
            context: .
            dockerfile: AdapterService/Dockerfile
        container_name: adapterservice
        ports:
           - "5002:80"
        networks:
           - microservicessolution-network
        environment:
           - ASPNETCORE_ENVIRONMENT=Docker

    cartservice:
        build: 
            context: .
            dockerfile: CartService/Dockerfile
        container_name: CartService
        ports:
           - "5003:80"
        depends_on:
           - sqlserver
           - rabbitmq
        networks:
           - microservicessolution-network
        environment:
           - ASPNETCORE_ENVIRONMENT=Docker

    checkoutservice:
        build: 
            context: .
            dockerfile: CheckoutService/Dockerfile
        container_name: CheckoutService
        ports:
           - "5004:80"
        depends_on:
           - sqlserver
           - rabbitmq
        networks:
           - microservicessolution-network
        environment:
           - ASPNETCORE_ENVIRONMENT=Docker
    

networks:
    microservicessolution-network:
        driver: bridge